### ISSUE TITLE
How is this (not) working ... ?

### ISSUE THREAD

**Issue by Woisek** [Gerschel/sd-web-ui-quickcss#19]
Somehow, I can't get my head around how this (should) work. Almost none of my edits for a custom CSS is not working.
For instance, I copied the masslevel.css to my_masslevel.css and edited some classes there.
For example this:
`.gr-button.gr-button-primary,
.dark .gr-button,
.dark .bg-gray-50,
.bg-gray-50,
.dark fieldset span.text-gray-500, .dark .gr-block.gr-box span.text-gray-500, .dark label.block span,  /* container names */
label,
.gr-form div /* number */
{
    background-image: transparent !important;
    background: 1;
    color: var(--ml-color-lightgrey);
}`

After applying and restart, nothing had changed. When I examine a button (.gr-button.gr-button-primary), the background is still 0 and var(--ml-color-lightgrey) says "... was not set". But obviously it is set in the css.
It looks like, the stylesheet wasn't loaded. Or whatever happend. That's the point where I ask myself, how is this working, when is the custom css inserted ... ?

Could anyone shed some light on this, please?

**Comment by Nacurutu** [comment]
Hi @Woisek 

May I ask, have u added the dark mode argument to your webui-user file?

Also, the way this works... First, if you have any user.css file in the root folder, you have to remove it... then, you need to open the extension, select the style, apply it, and then click on Reload UI.

Also, if you want to have the image, you need to use a style compatible with the image.

For the moment, the quickcss extension is only a way to help users to use their own customs CSS files, however, that doesn't means that every random CSS file will have all the thing the CSS files included in the style folders have.

It depends on the way the CSS file was made.

you can read the readme file and check what you need to have on your own CSS file to be compatible with the change of color, the background, or the sliders to change some UI parameters.

If you want to use a style compatible with the background, you can use Matrix, Alani, or Neon, and also, you can change the colors of them for your own color scheme directly from the extension.

@Gerschel is already working on a new version of the extension that will rely only on one file, allowing the user to change the colors and the style in a more simple n efficient way.

**Comment by Nacurutu** [comment]
@Gerschel I think is better to temporary remove the broken styles from the repo until the owners fix them to avoid this kind of issues with the users of the extension, what do you think?

**Comment by Woisek** [comment]
> Hi @Woisek

Hi Nacurutu!

> May I ask, have u added the dark mode argument to your webui-user file?

Not that I'm aware of. Like I wrote, I just made a copy of masslevel.css and began to edit this copy.

> Also, the way this works... First, if you have any user.css file in the root folder, you have to remove it... then, you need to open the extension, select the style, apply it, and then click on Reload UI.

Root of extension or WebUI? Either way, in both there are only "style.css" files, not "user.css".

> Also, if you want to have the image, you need to use a style compatible with the image.

What image do you mean?

> For the moment, the quickcss extension is only a way to help users to use their own custom CSS files, however, that doesn't means that every random CSS file will have all the thing the CSS files included in the style folders have.

OK, that's first important to know, second no problem. I'm coming from webdevelopment, so I can handle it. :)

> It depends on the way the CSS file was made.
> 
> Take a look at the readme file and check what you need to have on your own CSS file to be compatible with the change of color, the logo, or the sliders to change some UI parameters. Also, you can take open and check the Alani, Matrix and Neon CSS files to understand a little bit more about how the code is working now.

Basicly I only want to change colors, I don't need any images or logos.

> If you want to use a style compatible with the Logo, you can use Matrix, Alani, or Neon, and also, you can change the colors of them for your own color scheme directly from the extension.
> 
> @Gerschel is already working on a new version of the extension that will rely only on one file, allowing the user to change the colors and the style in a more simple n efficient way.

Then maybe it's better to wait for his new version before doing any experimenting. :)

> The background file included in the extension is just a blank one, you can put there your own files and use urs instead.
Yeah I saw this, thanks.

OK, maybe I will wait a bit for Gerschel and what he is coming up with.
Thanks for your response!

**Comment by Gerschel** [comment]
@Nacurutu I think we were left with it to adopt it. If I recall correctly, masslevel was based off the original one you did, just with different colors. And retrowave was based on someone else's who modified yours a little to keep range sliders with a fill (and used the css accent to change the color).  

I'm going to double check this right now, but I think all masslevel needs is to load neon, change the colors, and resave as masslevel.

**Comment by Nacurutu** [comment]
@Gerschel  Masslevel, yes, but as he changed some parts of the code, I can't just copy-paste mine.

Retrowave still has issues due to the last updates...

**Comment by Nacurutu** [comment]
> Not that I'm aware of. Like I wrote, I just made a copy of masslevel.css and began to edit this copy.
Add this --theme dark to your webui-user file 

`set COMMANDLINE_ARGS= --theme dark` that way you activate the dark theme of the webUI. The CSS files we use only mess with the dark theme mode.


> Root of extension or WebUI? Either way, in both there are only "style.css" files, not "user.css".
> 
Because the webUI dnst included an user.css file. that file must be created by the user. 
> 
> What image do you mean?
> 
The logo image.

![image](https://user-images.githubusercontent.com/18109442/215185473-c5a72d32-6510-4ef9-ac72-2ff751583b2a.png)

> Basicly I only want to change colors, I don't need any images or logos.

If that's is the case, load Neon Style and after u reload the webUI, the color options will appear in the extension, change them from there and save a new Style, named as you want, then, just select your new style an apply it from the extension. 


> I'm coming from webdevelopment, so I can handle it. :)

Awesome, if that is the case, you can help us if you want, because I don't know about CSS (or any coding) and I struggle a little but when I update my styles.. xD

**Comment by Woisek** [comment]
OK ... 

> > Add this --theme dark to your webui-user file

This was an important hint ... didn't read that, sorry. It seems now it works as it should. &)

> `set COMMANDLINE_ARGS= --theme dark` that way you activate the dark theme of the webUI. The CSS files we use only mess with the dark theme mode.

I see. Altough this works, from a webdesign standpoint, I would rather use a free name for that, like "custom" and build on that.
But it seem like that this function is not supportet (yet).

> > Root of extension or WebUI? Either way, in both there are only "style.css" files, not "user.css".
> Because the webUI dnst included an user.css file. that file must be created by the user.

OK ... haven't created one yet, but it seems to work nonetheless now ... ?!

> > What image do you mean?
> 
> The logo image.

Ah, OK.

> > Basicly I only want to change colors, I don't need any images or logos.
> 
> If that's is the case, load Neon Style and after u reload the webUI, the color options will appear in the extension, change them from there and save a new Style, named as you want, then, just select your new style an apply it from the extension.

Yes, this was my thought on how this works in the first place. And now that I got it working, I see that I miss some configurations, that are not included (yet).
IMHO, a good way to make this truely customizable, the CSS App page should contain all elements of the WebUI (like it does right now) and every single one should be customizable. Not just a few of them. That way, every one could create/edit his "dream theme" for the UI to the detail, no matter if bright or dark (so, need for a "pre-dark" setting ;) ).

> > I'm coming from webdevelopment, so I can handle it. :)
> 
> Awesome, if that is the case, you can help us if you want, because I don't know about CSS (or any coding) and I struggle a little bit when I update my styles.. xD

Yeah, sure. I could help where I can if needed. Mostly, I could give you hints and tips about how this extension could be structured, as you maybe already noticed. ;)

> Here https://github.com/Nacurutu/Dark-Themes-SD-WebUI-Automatic1111 you can find how my styles work and how to use them with or without the extension

I will check it.

> > Thanks for your response!
> 
> More than welcome!

Thanks again! :)

**Comment by Nacurutu** [comment]
> the CSS App page should contain all elements of the WebUI (like it does right now) and every single one should be customizable. 

That's the idea for the future, however, it is a little bit complicated for many reasons, the main one:

- The webUI uses Gradio, a premade "GUI" for python/js script apps, so, we depend a lot on what Gradio uses and what the webUI creator uses/code.

If they change anything, also the Style gets affected in most cases. So, we wanted to keep it as simple as we could, 

- It is a lot of effort to keep changing things every time an update changes the way the webUI is displayed.

I focused my files on backgrounds, some colors, buttons, and some modifications, however, I think in future updates we are going to add new things to customize.

> Thanks again! :)

More than welcome again.

PD: @Gerschel is the mastermind behind the quickcss extension.

**Comment by Woisek** [comment]
> > the CSS App page should contain all elements of the WebUI (like it does right now) and every single one should be customizable.
> 
> That's the idea for the future, however, it is a little bit complicated for many reasons, the main one:
> 
>     * The webUI uses Gradio, a premade "GUI" for python/js script apps, so, we depend a lot on what Gradio uses and what the webUI creator uses/code.

Yeah, I'm aware of that. Unfortunately it's not like a "real" website, where everything can be set up and then be done. :)
But with a bit thinking ahead, this should be managable.

> If they change anything, also the Style gets affected in most cases. So, we wanted to keep it as simple as we could,
> 
>     * It is a lot of effort to keep changing things every time an update changes the way the webUI is displayed.

If the naming convention isn't (always) changed, it shouldn't be manageable. Once a style is defined, it should be applied, no matter how the layout is done. Like on a real website.

> I focused my files on backgrounds, some colors, buttons, and some modifications, however, I think in future updates we are going to add new things to customize.

This would be awesome!
 
> > Thanks again! :)
> 
> More than welcome again.
> 
> PS: @Gerschel is the mastermind behind the quickcss extension. PS2: Glad to read that you got it to work now.

Yes, Kudos to him as well. Great work from all of you.

**Comment by Gerschel** [comment]
@Woisek Here is some relevant information.  
gradio has a stylesheet that they apply.  
Each component they provide is a bundle of elements, scripts and their own css.  
gradio provides a way for a user to inject some css during launch, the webui utilizes this by grabbing their default stylesheet in the root of the project and build a string, then sorting extensions alphanumerically, seeing if they have a stylesheet and append them to this string, then grabbing user.css in the root and appending to string.  Then it sets the css argument with this string as the value.  

The name quickcss was choosen so it had a letter near the end of the alphabet, so it's near last or at last in this string, except for user.css.
When applying a style, it makes a copy from "style_choices" subdirectory, and saves it in the extension directory just above, as "style.css", which is what the webui looks for. I did not want to override user.css, in case a user needed it so they can change specific things for themselves, for accessibility.  Also, in case some extension writer was unaware of each extension being allowed their own stylesheet and they write over that file.  

This app uses some comments in the css file as markers. I use python to read these markers, so it can build the correct type and amount of components that will work with gradio by default, I then use javascript to grab this long html style tag, and seek the start of section for our applied stylesheet. Some of the data, like how many color components and slider components is from a hidden component that hold these values, so it can grab the correct number of rules and use the correct logic to swap out the values (hex for colors and ints for sliders).  

Some of the issues we fight against, some of gradios prebuilt components use "!important", tailwind will redeclare the value of a variable over and over, inside of different rules, gradio tried working around some of these by using "!important" themselves, and they recommend to some to just do the same. So instead of extensions just increasing their specificity, they just call "!important". Before we learned of these things, we built this tool and sheets.  Modifying the tool and sheets has caused issues with others thinking that a stylesheet is already applied, so why do they need to reapply them, or they think that the stylesheet updates automatically when they update the ui. Then we have others that might not update the ui, but will on the extension.  

It sometimes becomes a challenge to decide which part of the app to update next. Building special effects in js take time. Do I build an effects pop-up for it's settings, a config file for autoloading effects choosen. Make the stylesheet save as is for next reload, but also make it hot swappable (will need a start and end marker to swap section, but if no start is found, append to style tag, how do I do this and respect user.css ( a blank stylesheet that is just a marker before user.css?)).

Making some of these changes will break current compatibility, so we will need to decide on a rule that says, if this is found in file, assume new rules, otherwise assume old rules.  
If we force automatically updating the applied style, there's a chance we will overwrite customizations they made. Do we try to keep their saved customizations in sync with the base theme it came from?  

This might mean we need to split up a css sheet into different pieces, and build them on load. One for having this type of hover effect, another for that type of hover effect. But then maintenance becomes large.  
If we remove the ability to save as a color theme, then this makes it easier to apply fixes as the webui renames classes, types and element id's and force the update. But then, we lose coolness factor.

**Comment by Woisek** [comment]
Hi Gerschel!

Thanks for this long indepth description. I understand what you are trying to say and maybe I'm too used to simple solutions, because for me, this all sounds terrible complex. :)
In my simple mind, maybe the path to treat Gradio like a website can give a easier solution.

Just talking:
Meaning to make your script act on the very last position and insert the custom css completely at last. As you know, the last loaded CSS overwrites everything else before defined and this is also realtime (i.e. I often use jQuery to inject styles at runtime without the need of reloading). Or think about the functionallity of Tempermonkey for webbrowsers.
Maybe this could be an approach to think about as it maybe circumvent some (possible) problems. :)
Again, just thinking loud. ;)

And again, thanks for your great work so far.
